# Generated by Django 4.1.1 on 2022-09-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Файлы'},
        ),
    ]
